[versions]
#groovy = "3.0.5"
##app
stdlib = "1.5.10"
reflect = "1.6.0"
coroutines = "1.3.9"

core-ktx = "1.7.0"
appcompat = "1.4.1"
material = "1.5.0"
constraintlayout = "2.0.1"
work-runtime = "2.7.0"
#jetpack
navigation = "2.4.2"
#navigation-compose = "2.4.0-alpha04"
annotation = "1.1.0"
lifecycle = "2.4.1"
lifecycle-extensions = "2.2.0"
kodein = "6.+"
timber = "4.7.1"
stetho = "1.5.0"
room = "2.4.1"
hilt = "2.37"
paging = "3.1.1"

#other
permissionsdispatcher = "4.8.0"
glide = "4.13.2"
materialdialogs = "3.3.0"
gson = "2.8.8"
colorpickerdialog = "1.1.0"
indicatorview = "4.0.1"
okhttp-logging = "4.7.2"
retrofit = "2.9.0"
countdown = "v3.0.5"






[libraries]
#groovy-core = { module = "org.codehaus.groovy:groovy", version.ref = "groovy" }
##app
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "stdlib" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "reflect" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "work-runtime" }
#navigagtion
navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
navigation-dynamic-feature = { module = "androidx.navigation:navigation-dynamic-features-fragment", version.ref = "navigation" }
navigation-test = { module = "androidx.navigation:navigation-testing", version.ref = "navigation" }
#navigation-compose-jetpack = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-common = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle" }
lifecycle-extention = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycle-extensions" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }

kodein-core = { module = "org.kodein.di:kodein-di-generic-jvm", version.ref = "kodein" }
kodein-android-x = { module = "org.kodein.di:kodein-di-framework-android-x", version.ref = "kodein" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
stetho-core = { module = "com.facebook.stetho:stetho", version.ref = "stetho" }
stetho-okhttp3 = { module = "com.facebook.stetho:stetho-okhttp3", version.ref = "stetho" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
hiltandroid = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hiltcompiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "paging" }



#other
permissionsdispatcher = { module = "com.github.permissions-dispatcher:permissionsdispatcher", version.ref = "permissionsdispatcher" }
permissionsdispatcherprocessor = { module = "com.github.permissions-dispatcher:permissionsdispatcher-processor", version.ref = "permissionsdispatcher" }
glide-core = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
materialdialogs-core = { module = "com.afollestad.material-dialogs:core", version.ref = "materialdialogs" }
materialdialogs-input = { module = "com.afollestad.material-dialogs:input", version.ref = "materialdialogs" }
materialdialogs-files = { module = "com.afollestad.material-dialogs:files", version.ref = "materialdialogs" }
materialdialogs-color = { module = "com.afollestad.material-dialogs:color", version.ref = "materialdialogs" }
materialdialogs-datetime = { module = "com.afollestad.material-dialogs:datetime", version.ref = "materialdialogs" }
materialdialogs-bottom = { module = "com.afollestad.material-dialogs:bottomsheets", version.ref = "materialdialogs" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
color-picker-dialog = { module = "com.jaredrummler:colorpicker", version.ref = "colorpickerdialog" }
indicator-view = { module = "com.github.dskyuno:IndicatorView", version.ref = "indicatorview" }
okhttp-logging = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp-logging" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
countdown = { module = "com.github.dskyuno:CountdownView", version.ref = "countdown" }




[bundles]
kotlin = ["kotlin-stdlib", "kotlin-reflect", "kotlin-coroutines"]
navigation = ["navigation-fragment", "navigation-ui", "navigation-dynamic-feature", "navigation-test"]
lifecycle = ["lifecycle-livedata", "lifecycle-viewmodel", "lifecycle-common", "lifecycle-extention", "lifecycle-runtime"]
kodein = ["kodein-core", "kodein-android-x"]
stetho = ["stetho-core", "stetho-okhttp3"]
room = ["room-runtime", "room-ktx"]
materialdialogs = ["materialdialogs-core", "materialdialogs-input", "materialdialogs-files", "materialdialogs-color", "materialdialogs-datetime", "materialdialogs-bottom"]
retrofit = ["retrofit", "retrofit-gson"]
